.IX Title "PHPDOCR 1"
.TH PHPDOCR 1 "2009-09-24" "phpdocr 0.1" ""
.\" For nroff, turn off justification.  Always turn off hyphenation; it makes
.\" way too many mistakes in technical documents.
.if n .ad l
.nh
.SH "NAME"
phpdocr \- a simple way to access PHP documentation from the command\-line
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
phpdocr \fI[\s-1OPTIONS\s0]\fR \fI[\s-1FUNCTION/CLASS/SEARCH\s0 \s-1STRING/\s0..]\fR
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\&\fBphpdocr\fR is a simple way to access \s-1PHP\s0 documentation from php.net
from the command-line.
.PP
It will download, prettify, and output \s-1PHP\s0 documentation for the
function/class/.. that was supplied on the command-line, much like
\&\fIperldoc\fR\|(1) does for \fIperl\fR\|(1) and ri does for \fIruby\fR\|(1). Unless you explicitly
tell it not to, phpdocr will also cache the documentation locally
for fast retrieval in the future.
.PP
phpdocr will send its output to your \s-1PAGER\s0 (if it is set, otherwise
it will default to less).
.PP
Links to further information are displayed in the output as [link\-text].
The link-text can be supplied to phpdocr in a subsequent invocation to
get more detailed information on that subject.
.SH "OPTIONS"
.IX Header "OPTIONS"
.IP "\fB\-h, \-\-help\fR" 4
.IX Item "-h, --help"
Display the help screen
.IP "\fB\-v, \-\-verbose\fR" 4
.IX Item "-v, --verbose"
Increase verbosity. When this is present phpdocr will tell you additional
information about what it is doing, ie. what page it is downloading at the
moment.
.IP "\fB\-o, \-\-comments\fR" 4
.IX Item "-o, --comments"
php.net has comments associated with most pages. By default phpdocr will
filter these away, however some times you may want to see them, in that
case supply \-\-comments and phpdocr will include them in its output.
.IP "\fB\-n, \-\-no\-cache\fR" 4
.IX Item "-n, --no-cache"
By default, phpdocr will cache documentation locally so that it can
easily be retrieved later without having to re-download it. This
parameter disables all caching (both reading from the cache, and
writing to the cache).
.IP "\fB\-m, \-\-mirror\fR \fI\s-1PATH\s0\fR" 4
.IX Item "-m, --mirror PATH"
By default phpdocr will connect to php.net. Use this to make it connect
to a specific mirror instead (ie. no2.php.net).
.IP "\fB\-\-man\fR" 4
.IX Item "--man"
Show the manpage. Normally 'man phpdocr' would do, but when phpdocr is
installed from a rubygem the phpdocr manpage isn't placed anywhere
in \fIman\fR\|(1)'s path, this will autodetect its location and issue man
directly on the phpdocr.1 file (and thus work even when 'man phpdocr'
does not).
.SH "FILES"
.IX Header "FILES"
\&\fI~/.phpdocr\fR \- this is where phpdocr will store any cached documentation.
It is safe to remove this directory, or any of its contents, at any time
if you need the disk space. phpdocr will simply re-download the documentation
next time you request it.
.SH "EXAMPLES"
.IX Header "EXAMPLES"
.IP "\fIphpdocr date\fR" 4
.IX Item "phpdocr date"
Will download and output the documentation for the date function, or
load it from cache if it has been cached.
.IP "\fIphpdocr \-u localtime\fR" 4
.IX Item "phpdocr -u localtime"
Will download and output the documentation for the localtime function
and the user comments associated with it. If an entry of the localtime
documentation with comments is already in cache, it will load it from
there instead.
.IP "\fIphpdocr \-n foreach\fR" 4
.IX Item "phpdocr -n foreach"
Will download and output the documentation for the foreach construct,
ignoring any cached information and not writing the result to the cache.
.SH "DEPENDENCIES"
.IX Header "DEPENDENCIES"
Requires one of: elinks, links2, links, w3m, html2text or lynx for \s-1HTML\s0 parsing.
.PP
Requires the mechanize rubygem for fetching stuff over \s-1HTTP\s0.
.SH "HELP/SUPPORT"
.IX Header "HELP/SUPPORT"
If you need help or support please visit the website at <http://random.zerodogg.org/phpdocr>
.SH "BUGS AND LIMITATIONS"
.IX Header "BUGS AND LIMITATIONS"
If you find a bug, please report it at <http://random.zerodogg.org/phpdocr/bugs>
.SH "AUTHOR"
.IX Header "AUTHOR"
\&\fBphpdocr\fR is written by Eskild Hustvedt <\fIcode at zerodogg dot org\fR>
.SH "LICENSE AND COPYRIGHT"
.IX Header "LICENSE AND COPYRIGHT"
Copyright (C) Eskild Hustvedt 2009
.PP
This is free software; see the source for copying conditions.  There is \s-1NO\s0
warranty; not even for \s-1MERCHANTABILITY\s0 or \s-1FITNESS\s0 \s-1FOR\s0 A \s-1PARTICULAR\s0 \s-1PURPOSE\s0.
