#!/usr/bin/ruby
# phpdocr
# Copyright (C) Eskild Hustvedt 2009
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Command-line parsing
require 'getoptlong'
require 'open3'
# www-mechanize is used for fetching from HTTP
require 'rubygems'
require 'mechanize'
# Application version
$version = 0.1

$includeUserNotes = false

def getURL (url)
	www = WWW::Mechanize.new
	return www.get(url).body
end

def lookup (name)
	data = getURL('http://php.net/manual-lookup.php?pattern='+name);
	hadFirst = false
	result = ''
	data.split(/\n/).each do |line|
		if hadFirst
			if ! $includeUserNotes && line =~ /User Contributed Notes/
				break
			end
			result.concat(line)
		elsif line =~ /ect1/
			hadFirst = true
		end
	end

	if ! hadFirst
		puts 'Could not find '+name+' in PHP documentation'
		return
	end

	cmd = [ 'html2text','-style','pretty' ]
	Open3.popen3(*cmd) { |stdin, stdout, stderr|
		stdin.puts(result)
		stdin.flush
		stdin.close

		result = stdout.gets(nil)
	}

	pager = ENV['PAGER']
	if pager == '' || pager == nil
		pager = 'less'
	end

	input = IO.popen(pager,'w')
	input.puts(result)
	input.close
end

lookup(ARGV.shift)
